### ISSUE TITLE
Review & Feedback System Bugs & Issues

### ISSUE THREAD

**Issue by hxddad** [demardefrozen10/EECS2311-Project#1]
1. For longer reviews, it would be nice if I started from the top of the textbox instead of being in the middle and extending into one long line.  It’s for me checking grammar and spelling. This is the same for the app feedback feature.

![image](https://github.com/demardefrozen10/EECS2311-Project/assets/127855239/d7609f94-c320-4f24-8f47-911a4edb391b)

2. It would be better to use buttons or multiple-choices for rating things from 1-5. What if I make a typo in my numbers (like accidentally typing ‘2w’)? I want people to see my ratings.

4. The “Leave Review” and “Give Review” buttons are confusing, sometimes I think “Leave Review" actually leaves the review for the given restaurant. I would at least change it to “Leave Feedback”.

![image](https://github.com/demardefrozen10/EECS2311-Project/assets/127855239/a818a1b2-d240-4dd2-8584-7ed295f9f1c0)

6. Review is accepted even after putting ratings more than 5 or less than 1 (or abnormally huge or small numbers) for food quality, service atmosphere and value for money. The review is accepted after putting 99 and -832473.

![image](https://github.com/demardefrozen10/EECS2311-Project/assets/127855239/488f2d14-e1ef-4733-881a-806c9244b1f7)

8. I don’t remember how many times I ate at popeyes; I want to put an option where I say “I don’t know/remember” or leave it blank, but it doesn't let me submit my review if I leave it blank. The same goes for “Items Eaten.”

![image](https://github.com/demardefrozen10/EECS2311-Project/assets/127855239/87e7cb14-ae26-4d9e-a72d-128918aa953a)

**Comment by NeelUpadhyay12** [comment]
Okay, I have fixed all the mistakes exactly how you wanted and posted the refined code in iteration 3, I did not change the leave feedback button since on top its already mentioned that it is feedback for us so we can just keep that it is not too big.

Thank you,
Neel
